### ISSUE TITLE
Export to Azure Purview

### ISSUE THREAD

**Issue by Mimetis** [Mimetis/ProjectY#8]
# Idea

Since all the engine has the same oupput format (Delta lake) we can imagine to export the dataset to Purview

## Today

For now, there is no way to have a clear overview of all landing zones from a single endpoint.

![image](https://user-images.githubusercontent.com/4592555/116399208-f48d6f00-a828-11eb-9eb2-b0fa38f1f77c.png)

## Expectation

Once a delta lake is created / updated after a successful pipeline, or after creating an engine, having a reference from pureview

![image](https://user-images.githubusercontent.com/4592555/116399086-d162bf80-a828-11eb-9da2-45fbe585a7fa.png)

## Assumptions
- Assuming Purview already is deployed
- SP config in Purview has been done (manually)
- SP has been added as a 'Storage data reader'
- SP secret has been added to the general Keyvault

## Tasks
- [x] Setup storage account scan for each LZ and each Engine
  - [x] setting up storage as a data source
  - [x] setting up a scan 
- [x] Connect ADF from each LZ in Purview
- [ ] 
- [ ]
